""" primary key  user id

Revision ID: 6f2444f0e5d7
Revises: 1b5f3f675b09
Create Date: 2025-03-19 12:39:34.017772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f2444f0e5d7'
down_revision = '1b5f3f675b09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('ix_user_user_id', ['user_id'], unique=False)

    # ### end Alembic commands ###
