"""Removing user token table

Revision ID: 9039c662ef5e
Revises: dfa3875331bb
Create Date: 2025-03-19 11:47:47.358843

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9039c662ef5e'
down_revision = 'dfa3875331bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_tokens', schema=None) as batch_op:
        batch_op.drop_index('refresh_token')

    op.drop_table('user_tokens')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_tokens',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('refresh_token', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('user_id', mysql.VARCHAR(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('user_tokens', schema=None) as batch_op:
        batch_op.create_index('refresh_token', ['refresh_token'], unique=True)

    # ### end Alembic commands ###
