"""Data type changed for user modal

Revision ID: dfa3875331bb
Revises: ad14d720bdcd
Create Date: 2025-03-19 11:33:09.855323

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dfa3875331bb'
down_revision = 'ad14d720bdcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=40),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.String(length=40),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
